[package]
name = "Syuparn/pangaea"
version = "0.12.0"
description = "A programming language for one-liner method chain lovers!"
license = "MIT"
repository = "https://github.com/Syuparn/Pangaea"
readme = "README.md"

[[module]]
name = "pangaea"
source = "pangaea.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "pangaea"
module = "pangaea"
runner = "wasi@unstable_"
