name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # NOTE: fetch all commits for changelogs, otherwise release note gets empty!
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set Tag to Env
        run: |
          git fetch --tags
          echo TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g") >> $GITHUB_ENV
      - name: Install git-chglog for Release Notes
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      # NOTE: process substutution cannot be used in goreleaser-action args
      - name: generate Release Note file
        run: |
          git-chglog ${{env.TAG}} > /tmp/release_note.md
          cat /tmp/release_note.md
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes /tmp/release_note.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
