name: Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Generate source files
      run: go generate

    - name: Build
      run: go build

    - name: GoTest
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: PangaeaTest
      run: ./pangaea test tests/

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
